// Mgmt
// Copyright (C) James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Additional permission under GNU GPL version 3 section 7
//
// If you modify this program, or any covered work, by linking or combining it
// with embedded mcl code and modules (and that the embedded mcl code and
// modules which link with this program, contain a copy of their source code in
// the authoritative form) containing parts covered by the terms of any other
// license, the licensors of this program grant you additional permission to
// convey the resulting work. Furthermore, the licensors of this program grant
// the original author, James Shubin, additional permission to update this
// additional permission if he deems it necessary to achieve the goals of this
// additional permission.

// Code generated by awsresgen. DO NOT EDIT.

//go:build !noaws

package aws

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/purpleidea/mgmt/engine"
	"github.com/purpleidea/mgmt/engine/traits"
	"github.com/purpleidea/mgmt/util/errwrap"
)

// Ensure these imports are used.
var _ = context.Background
var _ = json.Marshal
var _ = os.Getenv
var _ = strings.Join
var _ = errwrap.Wrapf
{{range .Resources}}
func init() {
	engine.RegisterResource({{quote .MgmtKind}}, func() engine.Res { return &{{.GoStructName}}{} })
}
{{end}}
{{range $res := .Resources}}
{{range .NestedStructs}}
// {{.GoName}} is a nested type for the {{$res.GoStructName}} resource.
type {{.GoName}} struct {
{{- range .Properties}}
	// {{.GoName}} is {{.Description}}
	{{.GoName}} {{.GoType}} `lang:"{{.LangTag}}" yaml:"{{.LangTag}}" json:"{{.JSONTag}}"`
{{- end}}
}
{{end}}

// {{.GoStructName}} is a {{.Description}}
// It is managed via the AWS Cloud Control API.
type {{.GoStructName}} struct {
	traits.Base // add the base methods without re-implementation

	init *engine.Init

	// State must be "exists" or "absent". Default: "exists".
	State string `lang:"state" yaml:"state" json:"-"`

	// Region is the AWS region for this resource. Falls back to AWS_REGION
	// or AWS_DEFAULT_REGION environment variables if empty.
	Region string `lang:"region" yaml:"region" json:"-"`
{{range .Properties}}
	// {{.GoName}} is {{.Description}}
	{{.GoName}} {{.GoType}} `lang:"{{.LangTag}}" yaml:"{{.LangTag}}" json:"{{.JSONTag}}"`
{{end}}
{{range .ReadOnlyProperties}}
	// {{.GoName}} is {{.Description}} (read-only)
	{{.GoName}} {{.GoType}} `lang:"{{.LangTag}}" yaml:"{{.LangTag}}" json:"{{.JSONTag}}"`
{{end}}
	// client is the Cloud Control API client.
	client *Client
}

// Default returns some sensible defaults for this resource.
func (obj *{{.GoStructName}}) Default() engine.Res {
	return &{{.GoStructName}}{
		State: "exists",
	}
}

// Validate if the params passed in are valid data.
func (obj *{{.GoStructName}}) Validate() error {
	if obj.State != "exists" && obj.State != "absent" {
		return fmt.Errorf("the State must be exists or absent, got: %s", obj.State)
	}

	region := obj.Region
	if region == "" {
		region = os.Getenv("AWS_REGION")
	}
	if region == "" {
		region = os.Getenv("AWS_DEFAULT_REGION")
	}
	if region == "" {
		return fmt.Errorf("no AWS region specified (set Region field or AWS_REGION env var)")
	}
{{range .Properties}}{{if .IsRequired}}
	if obj.{{.GoName}} == {{if eq .GoType "string"}}""{{else if eq .GoType "int64"}}0{{else if eq .GoType "float64"}}0{{else if eq .GoType "bool"}}false{{else}}nil{{end}} && obj.State == "exists" {
		return fmt.Errorf("the {{.GoName}} property is required")
	}
{{end}}{{end}}
	return nil
}

// Init runs some startup code for this resource.
func (obj *{{.GoStructName}}) Init(init *engine.Init) error {
	obj.init = init

	region := obj.Region
	if region == "" {
		region = os.Getenv("AWS_REGION")
	}
	if region == "" {
		region = os.Getenv("AWS_DEFAULT_REGION")
	}

	client, err := NewClient(context.TODO(), region)
	if err != nil {
		return errwrap.Wrapf(err, "error creating AWS client")
	}
	obj.client = client

	return nil
}

// Cleanup is run by the engine to clean up after the resource is done.
func (obj *{{.GoStructName}}) Cleanup() error {
	obj.client = nil
	return nil
}

// Watch is the primary listener for this resource and it outputs events. This
// resource requires the poll metaparam since the AWS Cloud Control API does not
// support push-based event notifications. Set Meta:poll to a desired interval.
func (obj *{{.GoStructName}}) Watch(ctx context.Context) error {
	// Send one initial event on startup so that CheckApply runs.
	if err := obj.init.Event(ctx); err != nil {
		return err
	}

	select {
	case <-ctx.Done(): // closed by the engine to signal shutdown
	}

	return nil
}

// CheckApply checks the resource state and optionally applies changes.
func (obj *{{.GoStructName}}) CheckApply(ctx context.Context, apply bool) (bool, error) {
	// Build the primary identifier.
	identifier := obj.primaryIdentifier()

	// Get the current state from AWS.
	current, err := obj.client.Get(ctx, {{quote .TypeName}}, identifier)
	if err != nil {
		return false, errwrap.Wrapf(err, "error getting resource")
	}

	// Handle absent state.
	if obj.State == "absent" {
		if current == nil {
			return true, nil // already absent
		}
		if !apply {
			return false, nil
		}
		obj.init.Logf("deleting resource")
		if err := obj.client.Delete(ctx, {{quote .TypeName}}, identifier); err != nil {
			return false, errwrap.Wrapf(err, "error deleting resource")
		}
		return false, nil
	}

	// State is "exists".
	desired := obj.desiredState()

	if current == nil {
		// Resource does not exist, create it.
		if !apply {
			return false, nil
		}
		obj.init.Logf("creating resource")
		if _, err := obj.client.Create(ctx, {{quote .TypeName}}, desired); err != nil {
			return false, errwrap.Wrapf(err, "error creating resource")
		}
		return false, nil
	}

	// Resource exists. Populate read-only fields from current state.
	obj.populateReadOnly(current)

	// Compare current with desired.
	patch := ComputePatch(current, desired, obj.readOnlyFields())
	if len(patch) == 0 {
		return true, nil // converged
	}
	if !apply {
		return false, nil
	}
{{if .SupportsUpdate}}
	obj.init.Logf("updating resource (%d changes)", len(patch))
	if err := obj.client.Update(ctx, {{quote .TypeName}}, identifier, patch); err != nil {
		return false, errwrap.Wrapf(err, "error updating resource")
	}
{{else}}
	return false, fmt.Errorf("resource %s does not support updates", {{quote .TypeName}})
{{end}}
	return false, nil
}

// Cmp compares two resources and returns an error if they are not equivalent.
func (obj *{{.GoStructName}}) Cmp(r engine.Res) error {
	res, ok := r.(*{{.GoStructName}})
	if !ok {
		return fmt.Errorf("not a %s", obj.Kind())
	}

	if obj.State != res.State {
		return fmt.Errorf("the State differs")
	}
	if obj.Region != res.Region {
		return fmt.Errorf("the Region differs")
	}
{{range .Properties}}
	if fmt.Sprintf("%v", obj.{{.GoName}}) != fmt.Sprintf("%v", res.{{.GoName}}) {
		return fmt.Errorf("the {{.GoName}} differs")
	}
{{end}}
	return nil
}

// {{.GoStructPrefix}}UID is the UID struct for {{.GoStructName}}.
type {{.GoStructPrefix}}UID struct {
	engine.BaseUID
	name string
}

// UIDs includes all params to make a unique identification of this object.
func (obj *{{.GoStructName}}) UIDs() []engine.ResUID {
	x := &{{.GoStructPrefix}}UID{
		BaseUID: engine.BaseUID{Name: obj.Name(), Kind: obj.Kind()},
		name:    obj.Name(),
	}
	return []engine.ResUID{x}
}

// UnmarshalYAML is the custom unmarshal handler for this struct. It is
// primarily useful for setting the defaults.
func (obj *{{.GoStructName}}) UnmarshalYAML(unmarshal func(interface{}) error) error {
	type rawRes {{.GoStructName}} // indirection to avoid infinite recursion

	def := obj.Default()                // get the default
	res, ok := def.(*{{.GoStructName}}) // put in the right format
	if !ok {
		return fmt.Errorf("could not convert to {{.GoStructName}}")
	}
	raw := rawRes(*res) // convert; the defaults go here

	if err := unmarshal(&raw); err != nil {
		return err
	}

	*obj = {{.GoStructName}}(raw) // restore from indirection with type conversion!
	return nil
}

// primaryIdentifier returns the primary identifier string for this resource.
func (obj *{{.GoStructName}}) primaryIdentifier() string {
{{- if eq (len .PrimaryIdentifierFields) 1}}
	return fmt.Sprintf("%v", obj.{{index .PrimaryIdentifierFields 0}})
{{- else if gt (len .PrimaryIdentifierFields) 1}}
	// Composite identifier: join with pipe separator.
	parts := []string{
	{{- range .PrimaryIdentifierFields}}
		fmt.Sprintf("%v", obj.{{.}}),
	{{- end}}
	}
	return strings.Join(parts, "|")
{{- else}}
	return obj.Name()
{{- end}}
}

// desiredState returns the desired state map for Cloud Control API calls. It
// excludes read-only properties.
func (obj *{{.GoStructName}}) desiredState() map[string]interface{} {
	// Marshal through JSON to get the right field names and omit empty
	// values.
	type noMethods {{.GoStructName}} // avoid method set
	data, err := json.Marshal((*noMethods)(obj))
	if err != nil {
		return map[string]interface{}{}
	}

	var all map[string]interface{}
	if err := json.Unmarshal(data, &all); err != nil {
		return map[string]interface{}{}
	}

	// Remove read-only fields.
	for k := range obj.readOnlyFields() {
		delete(all, k)
	}

	return all
}

// populateReadOnly fills in read-only fields from the current state map.
func (obj *{{.GoStructName}}) populateReadOnly(current map[string]interface{}) {
	_ = current // avoid unused variable if no read-only properties
{{range .ReadOnlyProperties}}
{{- if eq .GoType "string"}}
	if v, ok := current["{{.CFNName}}"]; ok {
		if s, ok := v.(string); ok {
			obj.{{.GoName}} = s
		}
		_ = v
	}
{{- else if eq .GoType "int64"}}
	if v, ok := current["{{.CFNName}}"]; ok {
		if f, ok := v.(float64); ok {
			obj.{{.GoName}} = int64(f)
		}
		_ = v
	}
{{- else if eq .GoType "float64"}}
	if v, ok := current["{{.CFNName}}"]; ok {
		if f, ok := v.(float64); ok {
			obj.{{.GoName}} = f
		}
		_ = v
	}
{{- else if eq .GoType "bool"}}
	if v, ok := current["{{.CFNName}}"]; ok {
		if b, ok := v.(bool); ok {
			obj.{{.GoName}} = b
		}
		_ = v
	}
{{- end}}
{{end}}
}

// readOnlyFields returns the set of read-only CFN property names.
func (obj *{{.GoStructName}}) readOnlyFields() map[string]bool {
	return map[string]bool{
{{- range .ReadOnlyProperties}}
		"{{.CFNName}}": true,
{{- end}}
	}
}
{{end}}
